name: CI

on: [pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9"]
        target: [x86_64]

    steps:
#      - name: Checkout source
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          environment-file: environment_conda.yaml
          environment-name: alluxio_test
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Conda info
        run: |
          conda list
          conda --version

      # alluxiocommon related
      - name: Build alluxiocommon wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release -i python${{ matrix.python-version }} --out dist -m rust/alluxiocommon/Cargo.toml
          manylinux: auto

      - name: Install all packages and Run AlluxioCommon tests
        shell: bash
        run: |
          set -e
          pip install .[tests]
          pip install alluxiocommon --no-index --find-links=dist/ --force-reinstall
          pip install pytest
          pytest -vv \
            --log-format="%(asctime)s %(levelname)s %(message)s" \
            --log-date-format="%H:%M:%S" \
          rust/alluxiocommon/tests/
          pytest -vv \
            --log-format="%(asctime)s %(levelname)s %(message)s" \
            --log-date-format="%H:%M:%S" \
          tests/

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.0
